import { Estimate, Customer, SiteVisit, Payment, AdminUser } from '@/types/estimate';

// 1. 관리자 모의 데이터 (3건)
export const mockAdminUsers: AdminUser[] = [
  {
    id: 'admin-owner-uuid-1111',
    email: 'owner@zeros.com',
    name: '홍길동 대표',
    role: 'owner',
    created_at: '2025-06-01T09:00:00Z'
  },
  {
    id: 'admin-admin-uuid-2222',
    email: 'admin@zeros.com',
    name: '김철수 부장',
    role: 'admin',
    created_at: '2025-06-15T09:00:00Z'
  },
  {
    id: 'admin-viewer-uuid-3333',
    email: 'viewer@zeros.com',
    name: '이영희 대리',
    role: 'viewer',
    created_at: '2025-07-01T09:00:00Z'
  }
];

// 2. 통합 고객 모의 데이터 (12건)
export const mockCustomers: Customer[] = [
  {
    id: 'cust-uuid-01',
    customer_name: '정지훈',
    company_name: 'ABC식품',
    phone: '010-1234-5678',
    email: 'jh.jung@abcfood.co.kr',
    site_address: '경기도 화성시 향남읍 식품공단로 42',
    customer_type: '식품 제조',
    customer_grade: '수주고객',
    total_requests: 3,
    total_won: 2,
    total_revenue: 85000000,
    last_contact_at: '2026-05-20T14:30:00Z',
    memo: '해당 식품공단 내 대규모 스팀 설비 주기적 개보수 계획 있음.',
    created_at: '2025-10-10T08:00:00Z'
  },
  {
    id: 'cust-uuid-02',
    customer_name: '박민지',
    company_name: '가나바이오',
    phone: '010-8765-4321',
    email: 'mj.park@ganabio.com',
    site_address: '인천광역시 연수구 송도과학로 120',
    customer_type: '제약·바이오',
    customer_grade: '중요고객',
    total_requests: 2,
    total_won: 1,
    total_revenue: 350000000,
    last_contact_at: '2026-05-25T11:00:00Z',
    memo: ' sanitary 크린 배관 스펙 매우 엄격. 다중 분기 및 레큘레이터 압력 유지가 중요함.',
    created_at: '2025-11-05T08:00:00Z'
  },
  {
    id: 'cust-uuid-03',
    customer_name: '이성호',
    company_name: '대성기계',
    phone: '010-5678-1234',
    email: 'sh.lee@daesungmac.com',
    site_address: '경상남도 창원시 성산구 공단로 88',
    customer_type: '중공업/조립',
    customer_grade: '재문의',
    total_requests: 2,
    total_won: 0,
    total_revenue: 0,
    last_contact_at: '2026-05-18T16:00:00Z',
    memo: '오일 냉각 배관 보수 및 호스 교체 2차 견적 단계 대기.',
    created_at: '2025-12-01T08:00:00Z'
  },
  {
    id: 'cust-uuid-04',
    customer_name: '최영준',
    company_name: '동방물류',
    phone: '010-4321-8765',
    email: 'yj.choi@dongbanglogis.com',
    site_address: '경기도 용인시 처인구 백암면 물류로 5',
    customer_type: '물류/창고',
    customer_grade: '보류고객',
    total_requests: 1,
    total_won: 0,
    total_revenue: 0,
    last_contact_at: '2026-02-10T10:00:00Z',
    memo: '물류센터 냉각 배관 누수로 출장 검토했으나 예산 문제로 투자 보류 상태.',
    created_at: '2026-01-15T08:00:00Z'
  },
  {
    id: 'cust-uuid-05',
    customer_name: '한석규',
    company_name: '세진화학',
    phone: '010-2222-3333',
    email: 'sk.han@sejinchem.com',
    site_address: '울산광역시 남구 화학로 300',
    customer_type: '화학/소재',
    customer_grade: '수주고객',
    total_requests: 2,
    total_won: 2,
    total_revenue: 45000000,
    last_contact_at: '2026-05-12T09:30:00Z',
    memo: '부식성 유체가 흘러 배관 재질에 대한 전문적인 내구성 비교 검토가 통과됨.',
    created_at: '2025-08-20T08:00:00Z'
  },
  {
    id: 'cust-uuid-06',
    customer_name: '김태균',
    company_name: '우일정밀',
    phone: '010-9999-8888',
    email: 'tk.kim@wooilprec.co.kr',
    site_address: '경기도 안산시 단원구 반월공단로 15',
    customer_type: '정밀 가공',
    customer_grade: '신규',
    total_requests: 1,
    total_won: 0,
    total_revenue: 0,
    last_contact_at: '2026-05-28T17:00:00Z',
    memo: '콤프레셔 라인 에어 호스 교체 온라인 간편 신청 고객.',
    created_at: '2026-05-28T17:00:00Z'
  },
  {
    id: 'cust-uuid-07',
    customer_name: '임수진',
    company_name: '태양에너지',
    phone: '010-7777-6666',
    email: 'sj.lim@sunenergy.co.kr',
    site_address: '충청남도 아산시 배방읍 에너지로 77',
    customer_type: '발전/에너지',
    customer_grade: '수주고객',
    total_requests: 1,
    total_won: 1,
    total_revenue: 120000000,
    last_contact_at: '2026-04-15T15:00:00Z',
    memo: '냉각수 순환 메니폴더 대형 배관 증설 수주 성공 건.',
    created_at: '2026-03-01T08:00:00Z'
  },
  {
    id: 'cust-uuid-08',
    customer_name: '송지호',
    company_name: '한강빌딩 관리단',
    phone: '010-4444-5555',
    email: 'jh.song@hangangbld.co.kr',
    site_address: '서울특별시 마포구 마포대로 150',
    customer_type: '상업 빌딩',
    customer_grade: '신규',
    total_requests: 1,
    total_won: 0,
    total_revenue: 0,
    last_contact_at: '2026-06-01T10:00:00Z',
    memo: '빌딩 지하 기계실 배관 부식 상태 보수 긴급 검토 요청.',
    created_at: '2026-06-01T10:00:00Z'
  },
  {
    id: 'cust-uuid-09',
    customer_name: '권동혁',
    company_name: '현대금속',
    phone: '010-1111-9999',
    email: 'dh.kwon@hdmetal.co.kr',
    site_address: '경상북도 포항시 남구 철강로 20',
    customer_type: '철강/비철',
    customer_grade: '보류고객',
    total_requests: 1,
    total_won: 0,
    total_revenue: 0,
    last_contact_at: '2026-01-20T14:00:00Z',
    memo: '용광로 수냉 배관 대수선 견적 검토 후 내부 품의 지연으로 보류.',
    created_at: '2026-01-05T08:00:00Z'
  },
  {
    id: 'cust-uuid-10',
    customer_name: '김현아',
    company_name: '제일제약',
    phone: '010-5555-8888',
    email: 'ha.kim@jeilpharma.com',
    site_address: '충청북도 청주시 흥덕구 오송생명로 25',
    customer_type: '제약·바이오',
    customer_grade: '수주고객',
    total_requests: 2,
    total_won: 1,
    total_revenue: 48000000,
    last_contact_at: '2026-05-10T11:00:00Z',
    memo: '제약 등급 크린 에어 라인 훅업 보수 성공 건.',
    created_at: '2025-09-15T08:00:00Z'
  },
  {
    id: 'cust-uuid-11',
    customer_name: '배우성',
    company_name: '태백메디컬',
    phone: '010-3333-7777',
    email: 'ws.bae@taebaekmed.com',
    site_address: '강원도 원주시 의료단지로 10',
    customer_type: '의료기기',
    customer_grade: '재문의',
    total_requests: 2,
    total_won: 0,
    total_revenue: 0,
    last_contact_at: '2026-05-30T10:00:00Z',
    memo: '질소 공급 유틸리티 배관 증설 2차 검토 진행중.',
    created_at: '2026-04-10T08:00:00Z'
  },
  {
    id: 'cust-uuid-12',
    customer_name: '강성민',
    company_name: '신라상가 상인회',
    phone: '010-6666-4444',
    email: 'sm.kang@shillasangga.co.kr',
    site_address: '서울특별시 중구 청계천로 200',
    customer_type: '일반 상가',
    customer_grade: '신규',
    total_requests: 1,
    total_won: 0,
    total_revenue: 0,
    last_contact_at: '2026-05-29T14:00:00Z',
    memo: '상가 메인 배관 보수 온라인 검토 신청.',
    created_at: '2026-05-29T14:00:00Z'
  }
];

// 3. 사전진단 견적 접수 모의 데이터 (30건 이상 - 최근 6개월 분산 및 13개 상태값 분포)
export const mockEstimates: Estimate[] = [
  {
    id: 'est-uuid-001',
    estimate_no: 'ZR-20251205-001',
    created_at: '2025-12-05T09:30:00Z',
    customer_name: '정지훈',
    company_name: 'ABC식품',
    phone: '010-1234-5678',
    email: 'jh.jung@abcfood.co.kr',
    site_address: '경기도 화성시 향남읍 식품공단로 42',
    customer_type: '식품 제조',
    work_type: '배관공사',
    site_type: '식품',
    work_purpose: '교체',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '1개월 이내',
    urgency: true,
    description: '공장 3라인 냉각수 입/출구 배관 노후화로 인한 부식 누수. 신속한 철거 후 SUS 교체 요청.',
    request_detail: '배관 65A 스케줄 10 SUS304 메인 라인 교체 검토.',
    estimate_category: 'medium',
    accuracy_grade: 'A',
    status: '수주성공',
    admin_memo: '현장 방문 실측 후 스펙 확정. 셧다운 일정을 일요일 하루로 단축 설계하여 계약 체결.',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 38000000,
    confirmed_contract_amount: 35000000,
    estimate_sent_at: '2025-12-10T15:00:00Z',
    contract_won_at: '2025-12-15T11:00:00Z',
    submitted_files: [
      {
        id: 'file-uuid-001',
        estimate_id: 'est-uuid-001',
        file_name: 'PND_CoolingLine_v1.pdf',
        file_type: 'application/pdf',
        file_url: '/mock-files/pnd.pdf',
        file_category: '도면',
        uploaded_at: '2025-12-05T09:30:00Z'
      }
    ]
  },
  {
    id: 'est-uuid-002',
    estimate_no: 'ZR-20251220-001',
    created_at: '2025-12-20T10:15:00Z',
    customer_name: '박민지',
    company_name: '가나바이오',
    phone: '010-8765-4321',
    email: 'mj.park@ganabio.com',
    site_address: '인천광역시 연수구 송도과학로 120',
    customer_type: '제약·바이오',
    work_type: '생산설비 배관 연결',
    site_type: '제약·바이오',
    work_purpose: '신규설치',
    expected_budget_range: '≥1억',
    desired_schedule: '3개월 이내',
    urgency: false,
    description: '바이오 배양기 5기 추가 도입에 따른 초순수(DIW) 루프 배관 분기 및 sanitary 훅업 정밀 용접 공사 검토.',
    request_detail: 'EP 배관 규격 및 크린룸 반입 계획 포함 수립 요망.',
    estimate_category: 'large',
    accuracy_grade: 'A',
    status: '수주성공',
    admin_memo: '초순수 순환 펌프 헤드 추가 및 루프 라인 압력 시뮬레이션 완료하여 1군 건설사 대비 경쟁력 있는 안으로 수주 성공.',
    assigned_admin: 'admin-owner-uuid-1111',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 350000000,
    confirmed_contract_amount: 350000000,
    estimate_sent_at: '2025-12-28T16:00:00Z',
    contract_won_at: '2026-01-08T10:00:00Z'
  },
  {
    id: 'est-uuid-003',
    estimate_no: 'ZR-20260110-001',
    created_at: '2026-01-10T14:20:00Z',
    customer_name: '한석규',
    company_name: '세진화학',
    phone: '010-2222-3333',
    email: 'sk.han@sejinchem.com',
    site_address: '울산광역시 남구 화학로 300',
    customer_type: '화학/소재',
    work_type: '노후배관교체',
    site_type: '공장',
    work_purpose: '교체',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '2개월 이내',
    urgency: false,
    description: '황산 이송 2번 배관 외벽 부식 발생. 내부식성 특수 재질(PTFE 라이닝 또는 테플론 코팅) 배관으로 전면 대체 진단.',
    request_detail: '배관 부식도 측정 및 재질 타당성 보고서 송부.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '수주성공',
    admin_memo: '테플론 라이닝 강관 WBS 제안 통과. 현장 밸브 마찰 손실 감안하여 1단계 보강 시공 수주.',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 45000000,
    confirmed_contract_amount: 45000000,
    estimate_sent_at: '2026-01-16T11:00:00Z',
    contract_won_at: '2026-01-22T15:00:00Z'
  },
  {
    id: 'est-uuid-004',
    estimate_no: 'ZR-20260118-001',
    created_at: '2026-01-18T11:00:00Z',
    customer_name: '최영준',
    company_name: '동방물류',
    phone: '010-4321-8765',
    email: 'yj.choi@dongbanglogis.com',
    site_address: '경기도 용인시 처인구 백암면 물류로 5',
    customer_type: '물류/창고',
    work_type: 'Utility 배관',
    site_type: '물류센터',
    work_purpose: '개선',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '2개월 이내',
    urgency: false,
    description: '물류센터 동절기 소화수 메인 배관 동파 방지용 메탈 히터 및 보온재 보수 설계.',
    request_detail: '보온재 두께 계산 및 전력 소모량 검토.',
    estimate_category: 'medium',
    accuracy_grade: 'C',
    status: '수주실패',
    admin_memo: '의뢰자가 내부 예산 편성 실패하여 사업 포기함. 보류 기간 경과 후 수주실패 종결.',
    assigned_admin: 'admin-viewer-uuid-3333',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 28000000,
    estimate_sent_at: '2026-01-25T14:00:00Z'
  },
  {
    id: 'est-uuid-005',
    estimate_no: 'ZR-20260205-001',
    created_at: '2026-02-05T09:00:00Z',
    customer_name: '이성호',
    company_name: '대성기계',
    phone: '010-5678-1234',
    email: 'sh.lee@daesungmac.com',
    site_address: '경상남도 창원시 성산구 공단로 88',
    customer_type: '중공업/조립',
    work_type: '장비설치',
    site_type: '공장',
    work_purpose: '신규설치',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '3개월 이내',
    urgency: false,
    description: '공장 내 대형 유압프레스 도입에 따른 메인 유압 공급 펌프 2기 안착 및 냉각 오일 순환관 조인트 진동 완충 설계.',
    request_detail: '장비 제원 기준 기초 베이스 강도 평가.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '보류',
    admin_memo: '독일산 프레스 반입 일정이 5개월 지연되어 견적 검토 일시적 보류 상태로 대기중.',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: false,
    payment_status: '미결제',
    estimated_amount: 60000000,
    estimate_sent_at: '2026-02-12T17:00:00Z'
  },
  {
    id: 'est-uuid-006',
    estimate_no: 'ZR-20260220-001',
    created_at: '2026-02-20T16:00:00Z',
    customer_name: '임수진',
    company_name: '태양에너지',
    phone: '010-7777-6666',
    email: 'sj.lim@sunenergy.co.kr',
    site_address: '충청남도 아산시 배방읍 에너지로 77',
    customer_type: '발전/에너지',
    work_type: '공장증설',
    site_type: '공장',
    work_purpose: '증설',
    expected_budget_range: '≥1억',
    desired_schedule: '6개월 이내',
    urgency: false,
    description: '냉각타워 증설에 따른 대형 메인 냉각수 분배 매니폴드 매칭 배관 분접 공사(Tie-in). 셧다운 마진 12시간 준수 필수.',
    request_detail: 'Hot-tapping 무중단 천공 공법 설계 병행 검토.',
    estimate_category: 'large',
    accuracy_grade: 'A',
    status: '수주성공',
    assigned_admin: 'admin-owner-uuid-1111',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 120000000,
    confirmed_contract_amount: 120000000,
    estimate_sent_at: '2026-02-28T10:00:00Z',
    contract_won_at: '2026-03-10T14:00:00Z'
  },
  {
    id: 'est-uuid-007',
    estimate_no: 'ZR-20260305-001',
    created_at: '2026-03-05T13:30:00Z',
    customer_name: '김현아',
    company_name: '제일제약',
    phone: '010-5555-8888',
    email: 'ha.kim@jeilpharma.com',
    site_address: '충청북도 청주시 흥덕구 오송생명로 25',
    customer_type: '제약·바이오',
    work_type: '기계실개선',
    site_type: '기계실',
    work_purpose: '개선',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '2개월 이내',
    urgency: false,
    description: '제약공장 유틸리티 기계실 내부 고압 냉량 가스 공급부 진동 흡수 및 편심 헤더 재배치 설계.',
    request_detail: '배관 서포트 부하 계산서 및 평면 스케치.',
    estimate_category: 'medium',
    accuracy_grade: 'A',
    status: '수주성공',
    admin_memo: '레이저 스캐너 활용한 기존 간섭 시각화 제시로 신뢰 획득. 성공적으로 수주.',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 48000000,
    confirmed_contract_amount: 48000000,
    estimate_sent_at: '2026-03-12T16:00:00Z',
    contract_won_at: '2026-03-20T11:00:00Z'
  },
  {
    id: 'est-uuid-008',
    estimate_no: 'ZR-20260322-001',
    created_at: '2026-03-22T10:45:00Z',
    customer_name: '권동혁',
    company_name: '현대금속',
    phone: '010-1111-9999',
    email: 'dh.kwon@hdmetal.co.kr',
    site_address: '경상북도 포항시 남구 철강로 20',
    customer_type: '철강/비철',
    work_type: 'CAPEX 개·증설 검토',
    site_type: '공장',
    work_purpose: '개선',
    expected_budget_range: '≥1억',
    desired_schedule: '6개월 이내',
    urgency: false,
    description: '용광로 냉각 공급 수관 및 가스 연소 덕트 교체 관련 기획 단계 예산 상한선(WBS) 수립 검토.',
    request_detail: '컨셉 공정 타당성 분석.',
    estimate_category: 'large',
    accuracy_grade: 'D',
    status: '보류',
    admin_memo: '고압 가스 사용에 따른 소방/인허가 법적 규제가 까다로워 대관 인허가 사전검토로 보류 중.',
    assigned_admin: 'admin-owner-uuid-1111',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 150000000,
    estimate_sent_at: '2026-03-30T15:00:00Z'
  },
  {
    id: 'est-uuid-009',
    estimate_no: 'ZR-20260402-001',
    created_at: '2026-04-02T14:00:00Z',
    customer_name: '배우성',
    company_name: '태백메디컬',
    phone: '010-3333-7777',
    email: 'ws.bae@taebaekmed.com',
    site_address: '강원도 원주시 의료단지로 10',
    customer_type: '의료기기',
    work_type: '배관공사',
    site_type: '제약·바이오',
    work_purpose: '증설',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '1개월 이내',
    urgency: true,
    description: '청정 4실 질소 공급 배관 1라인 추가 분기 공사 및 배관 오염물 파티클 방지용 EP 파이프 설계 검토.',
    request_detail: 'Ep 파이프 용접 품질 시나리오 포함.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '견적서 송부완료',
    admin_memo: 'EP 자재 유통 단가 급변에 따라 유효기간 14일로 견적서 발송 후 수주 협상 진행 중.',
    assigned_admin: 'admin-viewer-uuid-3333',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 32000000,
    estimate_sent_at: '2026-04-08T11:00:00Z'
  },
  {
    id: 'est-uuid-010',
    estimate_no: 'ZR-20260415-001',
    created_at: '2026-04-15T16:20:00Z',
    customer_name: '김태균',
    company_name: '우일정밀',
    phone: '010-9999-8888',
    email: 'tk.kim@wooilprec.co.kr',
    site_address: '경기도 안산시 단원구 반월공단로 15',
    customer_type: '정밀 가공',
    work_type: '장비설치',
    site_type: '공장',
    work_purpose: '교체',
    expected_budget_range: '≤1,000만',
    desired_schedule: '2주 이내',
    urgency: true,
    description: '기존 에어 콤프레셔 진동으로 인한 연결 배관 절단 누출. 흡진 자바라 호스 교체 및 압력계 신설 신속 검토.',
    request_detail: '에어 호스 고장 고온 내구 규격 진단.',
    estimate_category: 'small',
    accuracy_grade: 'C',
    status: '견적서 송부완료',
    admin_memo: '에바라 사 규격 매칭 호스 적용 견적 산정. 온라인 간편 제출 완료함.',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: false,
    payment_status: '미결제',
    estimated_amount: 3500000,
    estimate_sent_at: '2026-04-16T15:00:00Z'
  },
  // --- 11건 ~ 30건 추가 생성 ---
  {
    id: 'est-uuid-011',
    estimate_no: 'ZR-20260418-001',
    created_at: '2026-04-18T10:00:00Z',
    customer_name: '강성민',
    company_name: '신라상가 상인회',
    phone: '010-6666-4444',
    email: 'sm.kang@shillasangga.co.kr',
    site_address: '서울특별시 중구 청계천로 200',
    customer_type: '일반 상가',
    work_type: '노후배관교체',
    site_type: '상가',
    work_purpose: '개선',
    expected_budget_range: '≤1,000만',
    desired_schedule: '1개월 이내',
    urgency: false,
    description: '상가 지하 공용 집수정 펌프 배출관 누수로 인한 악취 및 바닥 오염. 배관 전면 철거 후 PVC 신설 검토.',
    estimate_category: 'small',
    accuracy_grade: 'C',
    status: '견적서 송부완료',
    assigned_admin: 'admin-viewer-uuid-3333',
    payment_required: false,
    payment_status: '미결제',
    estimated_amount: 6500000,
    estimate_sent_at: '2026-04-20T14:00:00Z'
  },
  {
    id: 'est-uuid-012',
    estimate_no: 'ZR-20260422-001',
    created_at: '2026-04-22T09:30:00Z',
    customer_name: '정지훈',
    company_name: 'ABC식품',
    phone: '010-1234-5678',
    email: 'jh.jung@abcfood.co.kr',
    site_address: '경기도 화성시 향남읍 식품공단로 42',
    customer_type: '식품 제조',
    work_type: '기계실개선',
    site_type: '식품',
    work_purpose: '개선',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '2개월 이내',
    urgency: false,
    description: '공장 칠러 기계실 입/출구 냉각수 통합 매니폴더 밸브 노후화로 인한 열림 상태 고착. 1차 바이패스 라인 증설 설계.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '견적서 송부완료',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 50000000,
    estimate_sent_at: '2026-04-28T16:00:00Z'
  },
  {
    id: 'est-uuid-013',
    estimate_no: 'ZR-20260425-001',
    created_at: '2026-04-25T14:30:00Z',
    customer_name: '박민지',
    company_name: '가나바이오',
    phone: '010-8765-4321',
    email: 'mj.park@ganabio.com',
    site_address: '인천광역시 연수구 송도과학로 120',
    customer_type: '제약·바이오',
    work_type: 'Utility 배관',
    site_type: '제약·바이오',
    work_purpose: '교체',
    expected_budget_range: '≥1억',
    desired_schedule: '3개월 이내',
    urgency: false,
    description: '배양 1동 청정 스팀 공급용 Sanitary SUS 배관 라인 교체 및 진공 차단 해제 시스템 검토.',
    estimate_category: 'large',
    accuracy_grade: 'A',
    status: '견적서 작성중',
    assigned_admin: 'admin-owner-uuid-1111',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 140000000
  },
  {
    id: 'est-uuid-014',
    estimate_no: 'ZR-20260429-001',
    created_at: '2026-04-29T11:00:00Z',
    customer_name: '배우성',
    company_name: '태백메디컬',
    phone: '010-3333-7777',
    email: 'ws.bae@taebaekmed.com',
    site_address: '강원도 원주시 의료단지로 10',
    customer_type: '의료기기',
    work_type: '장비설치',
    site_type: '공장',
    work_purpose: '신규설치',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '3개월 이내',
    urgency: false,
    description: '공정 클린룸 내 진공 포장기 4대 신설 및 후단 진공 흡입 매니폴더 펌프 가동 연결 배관 라인 구축.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '견적서 작성중',
    assigned_admin: 'admin-viewer-uuid-3333',
    payment_required: true,
    payment_status: '결제완료',
    estimated_amount: 45000000
  },
  {
    id: 'est-uuid-015',
    estimate_no: 'ZR-20260502-001',
    created_at: '2026-05-02T13:00:00Z',
    customer_name: '송지호',
    company_name: '한강빌딩 관리단',
    phone: '010-4444-5555',
    email: 'jh.song@hangangbld.co.kr',
    site_address: '서울특별시 마포구 마포대로 150',
    customer_type: '상업 빌딩',
    work_type: '기계실개선',
    site_type: '기계실',
    work_purpose: '교체',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '2주 이내',
    urgency: true,
    description: '빌딩 지하 기계실 난방 스팀 분기 헤더 미세 누수 발견. 노후 플랜지 교체 및 용접 용융 접합 보수 검토.',
    estimate_category: 'medium',
    accuracy_grade: 'A',
    status: '현장방문 완료',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제완료'
  },
  {
    id: 'est-uuid-016',
    estimate_no: 'ZR-20260505-001',
    created_at: '2026-05-05T09:30:00Z',
    customer_name: '한석규',
    company_name: '세진화학',
    phone: '010-2222-3333',
    email: 'sk.han@sejinchem.com',
    site_address: '울산광역시 남구 화학로 300',
    customer_type: '화학/소재',
    work_type: '배관공사',
    site_type: '공장',
    work_purpose: '증설',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '1개월 이내',
    urgency: false,
    description: '화학공정 C동 솔벤트 공급 메인 라인 분기 밸브 추가 및 누설 방지 하이-씰 플랜지 마감 설계 검토.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '현장방문 예정',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제완료'
  },
  {
    id: 'est-uuid-017',
    estimate_no: 'ZR-20260508-001',
    created_at: '2026-05-08T15:00:00Z',
    customer_name: '정지훈',
    company_name: 'ABC식품',
    phone: '010-1234-5678',
    email: 'jh.jung@abcfood.co.kr',
    site_address: '경기도 화성시 향남읍 식품공단로 42',
    customer_type: '식품 제조',
    work_type: '공장증설',
    site_type: '식품',
    work_purpose: '증설',
    expected_budget_range: '≥1억',
    desired_schedule: '6개월 이내',
    urgency: false,
    description: '소스 가열 교반기 4대 도입에 따른 180도 스팀 공급 관로 증설 및 응축수 리턴 서브 라인 매핑.',
    estimate_category: 'large',
    accuracy_grade: 'A',
    status: '방문일정 조율중',
    assigned_admin: 'admin-owner-uuid-1111',
    payment_required: true,
    payment_status: '결제완료'
  },
  {
    id: 'est-uuid-018',
    estimate_no: 'ZR-20260512-001',
    created_at: '2026-05-12T11:00:00Z',
    customer_name: '임수진',
    company_name: '태양에너지',
    phone: '010-7777-6666',
    email: 'sj.lim@sunenergy.co.kr',
    site_address: '충청남도 아산시 배방읍 에너지로 77',
    customer_type: '발전/에너지',
    work_type: 'Utility 배관',
    site_type: '공장',
    work_purpose: '개선',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '1개월 이내',
    urgency: false,
    description: '냉각타워 인입 스크레이핑 여과기 후단 차압 센서 추가 장착을 위한 바이패스 배관 신설 진단.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '출장견적 결제대기',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제대기'
  },
  {
    id: 'est-uuid-019',
    estimate_no: 'ZR-20260515-001',
    created_at: '2026-05-15T14:30:00Z',
    customer_name: '박민지',
    company_name: '가나바이오',
    phone: '010-8765-4321',
    email: 'mj.park@ganabio.com',
    site_address: '인천광역시 연수구 송도과학로 120',
    customer_type: '제약·바이오',
    work_type: 'CAPEX 개·증설 검토',
    site_type: '공장',
    work_purpose: '증설',
    expected_budget_range: '≥1억',
    desired_schedule: '6개월 이내',
    urgency: false,
    description: '완제 포장 공장 신설 프로젝트 배관 공종 사전 기획 타당성 검토 및 실행 단가 WBS 밴드 산출.',
    estimate_category: 'large',
    accuracy_grade: 'C',
    status: '검토중',
    assigned_admin: 'admin-owner-uuid-1111',
    payment_required: true,
    payment_status: '결제완료'
  },
  {
    id: 'est-uuid-020',
    estimate_no: 'ZR-20260518-001',
    created_at: '2026-05-18T09:30:00Z',
    customer_name: '이성호',
    company_name: '대성기계',
    phone: '010-5678-1234',
    email: 'sh.lee@daesungmac.com',
    site_address: '경상남도 창원시 성산구 공단로 88',
    customer_type: '중공업/조립',
    work_type: '생산설비 배관 연결',
    site_type: '공장',
    work_purpose: '개선',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '1개월 이내',
    urgency: false,
    description: '대형 밀링기 3대 공급 절삭유 쿨런트 공급/회수 호스 배관 고압 유량 밸브 차폐 구조 개선 설계.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '검토중',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제완료'
  },
  {
    id: 'est-uuid-021',
    estimate_no: 'ZR-20260520-001',
    created_at: '2026-05-20T16:00:00Z',
    customer_name: '배우성',
    company_name: '태백메디컬',
    phone: '010-3333-7777',
    email: 'ws.bae@taebaekmed.com',
    site_address: '강원도 원주시 의료단지로 10',
    customer_type: '의료기기',
    work_type: '노후배관교체',
    site_type: '공장',
    work_purpose: '교체',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '2개월 이내',
    urgency: false,
    description: '공정 폐수 중화 조 전단 산/알칼리 유하 배관 고온 누설로 재질 교체(PP 또는 PVDF 적용성 진단).',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '검토중',
    assigned_admin: 'admin-viewer-uuid-3333',
    payment_required: true,
    payment_status: '결제완료'
  },
  {
    id: 'est-uuid-022',
    estimate_no: 'ZR-20260522-001',
    created_at: '2026-05-22T11:00:00Z',
    customer_name: '최영준',
    company_name: '동방물류',
    phone: '010-4321-8765',
    email: 'yj.choi@dongbanglogis.com',
    site_address: '경기도 용인시 처인구 백암면 물류로 5',
    customer_type: '물류/창고',
    work_type: '장비설치',
    site_type: '물류센터',
    work_purpose: '신규설치',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '1개월 이내',
    urgency: false,
    description: '물류센터 화물차 고압 가습 스팀 발생 보일러 장비 1대 진입 반입로 확보 및 호스 드레인 배관 안착 설계.',
    estimate_category: 'medium',
    accuracy_grade: 'C',
    status: '검토중',
    assigned_admin: 'admin-viewer-uuid-3333',
    payment_required: true,
    payment_status: '결제완료'
  },
  {
    id: 'est-uuid-023',
    estimate_no: 'ZR-20260524-001',
    created_at: '2026-05-24T14:00:00Z',
    customer_name: '한석규',
    company_name: '세진화학',
    phone: '010-2222-3333',
    email: 'sk.han@sejinchem.com',
    site_address: '울산광역시 남구 화학로 300',
    customer_type: '화학/소재',
    work_type: '배관공사',
    site_type: '공장',
    work_purpose: '교체',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '2주 이내',
    urgency: true,
    description: '케미칼 이송용 80A 밸브 플랜지 가스켓 노화 미세 유출 보수. 신속 가스켓 스펙 선정 요청.',
    estimate_category: 'medium',
    accuracy_grade: 'B',
    status: '검토중',
    assigned_admin: 'admin-admin-uuid-2222',
    payment_required: true,
    payment_status: '결제완료'
  },
  {
    id: 'est-uuid-024',
    estimate_no: 'ZR-20260525-001',
    created_at: '2026-05-25T10:00:00Z',
    customer_name: '정지훈',
    company_name: 'ABC식품',
    phone: '010-1234-5678',
    email: 'jh.jung@abcfood.co.kr',
    site_address: '경기도 화성시 향남읍 식품공단로 42',
    customer_type: '식품 제조',
    work_type: 'Utility 배관',
    site_type: '식품',
    work_purpose: '개선',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '1개월 이내',
    urgency: false,
    description: '공장 급수 메인 유량 계측기 장착부 지중화 구간 노출 및 바이패스 강관 배치 사전 진단.',
    estimate_category: 'medium',
    accuracy_grade: 'A',
    status: '접수완료',
    payment_required: false,
    payment_status: '미결제'
  },
  {
    id: 'est-uuid-025',
    estimate_no: 'ZR-20260526-001',
    created_at: '2026-05-26T15:30:00Z',
    customer_name: '박민지',
    company_name: '가나바이오',
    phone: '010-8765-4321',
    email: 'mj.park@ganabio.com',
    site_address: '인천광역시 연수구 송도과학로 120',
    customer_type: '제약·바이오',
    work_type: '생산설비 배관 연결',
    site_type: '제약·바이오',
    work_purpose: '신규설치',
    expected_budget_range: '≥1억',
    desired_schedule: '3개월 이내',
    urgency: false,
    description: '신축 무균 충진라인 전용 고압 에어 노즐 및 세척용 질소 훅업 분접 노즐 패널 브래킷 장착 설계.',
    estimate_category: 'large',
    status: '접수완료',
    payment_required: false,
    payment_status: '미결제'
  },
  {
    id: 'est-uuid-026',
    estimate_no: 'ZR-20260527-001',
    created_at: '2026-05-27T11:00:00Z',
    customer_name: '이성호',
    company_name: '대성기계',
    phone: '010-5678-1234',
    email: 'sh.lee@daesungmac.com',
    site_address: '경상남도 창원시 성산구 공단로 88',
    customer_type: '중공업/조립',
    work_type: '장비설치',
    site_type: '공장',
    work_purpose: '이전',
    expected_budget_range: '1,000만~1억',
    desired_schedule: '1개월 이내',
    urgency: false,
    description: '본사 도장 설비 분무 펌프 장비 이전 안착 및 쿨런트 회로 배관 신축 분기 홉업 설계.',
    estimate_category: 'medium',
    status: '접수완료',
    payment_required: false,
    payment_status: '미결제'
  },
  {
    id: 'est-uuid-027',
    estimate_no: 'ZR-20260528-001',
    created_at: '2026-05-28T17:00:00Z',
    customer_name: '김태균',
    company_name: '우일정밀',
    phone: '010-9999-8888',
    email: 'tk.kim@wooilprec.co.kr',
    site_address: '경기도 안산시 단원구 반월공단로 15',
    customer_type: '정밀 가공',
    work_type: '배관공사',
    site_type: '공장',
    work_purpose: '개선',
    expected_budget_range: '≤1,000만',
    desired_schedule: '2주 이내',
    urgency: false,
    description: '가공기 냉각제 노출 분사 헤드 호스 밸브 교환. 온라인 간편 신청.',
    estimate_category: 'small',
    status: '접수완료',
    payment_required: false,
    payment_status: '미결제'
  },
  {
    id: 'est-uuid-028',
    estimate_no: 'ZR-20260529-001',
    created_at: '2026-05-29T14:00:00Z',
    customer_name: '강성민',
    company_name: '신라상가 상인회',
    phone: '010-6666-4444',
    email: 'sm.kang@shillasangga.co.kr',
    site_address: '서울특별시 중구 청계천로 200',
    customer_type: '일반 상가',
    work_type: '배관공사',
    site_type: '상가',
    work_purpose: '긴급보수',
    expected_budget_range: '≤1,000만',
    desired_schedule: '1주 이내',
    urgency: true,
    description: '2층 남성 화장실 공용 온수 환탕 배관 나사부 누수 고임. 긴급 실리콘 테이프 및 볼 밸브 잠금 보수 요망.',
    estimate_category: 'small',
    status: '접수완료',
    payment_required: false,
    payment_status: '미결제'
  },
  {
    id: 'est-uuid-029',
    estimate_no: 'ZR-20260530-001',
    created_at: '2026-05-30T10:00:00Z',
    customer_name: '배우성',
    company_name: '태백메디컬',
    phone: '010-3333-7777',
    email: 'ws.bae@taebaekmed.com',
    site_address: '강원도 원주시 의료단지로 10',
    customer_type: '의료기기',
    work_type: 'Utility 배관',
    site_type: '공장',
    work_purpose: '개선',
    expected_budget_range: '모름',
    desired_schedule: '2개월 이내',
    urgency: false,
    description: '공장 옥상 칠러 탱크 노출 냉각수 밸브 보온 외장재 노후 탈락. UV 보온 외장 시팅 시공 제안.',
    estimate_category: 'unknown',
    status: '접수완료',
    payment_required: false,
    payment_status: '미결제'
  },
  {
    id: 'est-uuid-030',
    estimate_no: 'ZR-20260601-001',
    created_at: '2026-06-01T10:00:00Z',
    customer_name: '송지호',
    company_name: '한강빌딩 관리단',
    phone: '010-4444-5555',
    email: 'jh.song@hangangbld.co.kr',
    site_address: '서울특별시 마포구 마포대로 150',
    customer_type: '상업 빌딩',
    work_type: '배관공사',
    site_type: '기계실',
    work_purpose: '긴급보수',
    expected_budget_range: '모름',
    desired_schedule: '1주 이내',
    urgency: true,
    description: '지하 2층 지하수 배출 횡주관 스케일로 막힘 의심. 세척 고압 워터 제팅 및 신설 검토.',
    estimate_category: 'unknown',
    status: '접수완료',
    payment_required: false,
    payment_status: '미결제'
  }
];

// 4. 결제 기록 모의 데이터 (15건)
export const mockPayments: Payment[] = [
  {
    id: 'pay-uuid-001',
    estimate_id: 'est-uuid-001',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'toss',
    transaction_id: 'TX_TOSS_11112222',
    paid_at: '2025-12-06T14:00:00Z',
    created_at: '2025-12-05T09:30:00Z',
    memo: 'ABC식품 향남공장 냉각수 배관 현장 실측 출장비.'
  },
  {
    id: 'pay-uuid-002',
    estimate_id: 'est-uuid-002',
    payment_type: '프로젝트 사전진단비',
    amount: 1500000,
    payment_status: '결제완료',
    payment_provider: 'card',
    transaction_id: 'TX_CARD_55556666',
    paid_at: '2025-12-21T16:30:00Z',
    created_at: '2025-12-20T10:15:00Z',
    memo: '가나바이오 배양기 DIW 배관 사전진단 엔지니어링 리포팅 비용.'
  },
  {
    id: 'pay-uuid-003',
    estimate_id: 'est-uuid-003',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'bank',
    transaction_id: 'TX_BANK_99990000',
    paid_at: '2026-01-11T13:00:00Z',
    created_at: '2026-01-10T14:20:00Z',
    memo: '세진화학 울산공장 황산이송관 특수재질 분석 및 실측비.'
  },
  {
    id: 'pay-uuid-004',
    estimate_id: 'est-uuid-004',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'bank',
    transaction_id: 'TX_BANK_22221111',
    paid_at: '2026-01-19T10:00:00Z',
    created_at: '2026-01-18T11:00:00Z',
    memo: '동방물류 소화관 동파 방지 보수 출장비 (환불 사유 없음. 수주실패 종결됨.)'
  },
  {
    id: 'pay-uuid-005',
    estimate_id: 'est-uuid-006',
    payment_type: '프로젝트 사전진단비',
    amount: 1000000,
    payment_status: '결제완료',
    payment_provider: 'toss',
    transaction_id: 'TX_TOSS_88889999',
    paid_at: '2026-02-21T11:00:00Z',
    created_at: '2026-02-20T16:00:00Z',
    memo: '태양에너지 냉각타워 매니폴드 셧다운 최소화 기법 WBS 분석비.'
  },
  {
    id: 'pay-uuid-006',
    estimate_id: 'est-uuid-007',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'card',
    transaction_id: 'TX_CARD_22334455',
    paid_at: '2026-03-06T11:00:00Z',
    created_at: '2026-03-05T13:30:00Z',
    memo: '제일제약 오송공장 고압 가스 헤더 재배치 레이저 실측비.'
  },
  {
    id: 'pay-uuid-007',
    estimate_id: 'est-uuid-008',
    payment_type: '프로젝트 사전진단비',
    amount: 1500000,
    payment_status: '결제완료',
    payment_provider: 'bank',
    transaction_id: 'TX_BANK_77778888',
    paid_at: '2026-03-23T14:00:00Z',
    created_at: '2026-03-22T10:45:00Z',
    memo: '현대금속 포항공장 용광로 WBS 단가 검토비.'
  },
  {
    id: 'pay-uuid-008',
    estimate_id: 'est-uuid-009',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'toss',
    transaction_id: 'TX_TOSS_77665544',
    paid_at: '2026-04-03T10:00:00Z',
    created_at: '2026-04-02T14:00:00Z',
    memo: '태백메디컬 원주 클린룸 배관 추가 분기 출장 실측비.'
  },
  {
    id: 'pay-uuid-009',
    estimate_id: 'est-uuid-012',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'bank',
    transaction_id: 'TX_BANK_33334444',
    paid_at: '2026-04-23T11:00:00Z',
    created_at: '2026-04-22T09:30:00Z',
    memo: 'ABC식품 칠러 기계실 바이패스관 추가 실측비.'
  },
  {
    id: 'pay-uuid-010',
    estimate_id: 'est-uuid-013',
    payment_type: '프로젝트 사전진단비',
    amount: 1200000,
    payment_status: '결제완료',
    payment_provider: 'card',
    transaction_id: 'TX_CARD_99992222',
    paid_at: '2026-04-26T16:00:00Z',
    created_at: '2026-04-25T14:30:00Z',
    memo: '가나바이오 청정 스팀 Sanitary 배관 종합 리포트비.'
  },
  {
    id: 'pay-uuid-011',
    estimate_id: 'est-uuid-014',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'toss',
    transaction_id: 'TX_TOSS_22331199',
    paid_at: '2026-04-30T10:00:00Z',
    created_at: '2026-04-29T11:00:00Z',
    memo: '태백메디컬 진공포장기 라인 실측 출장비.'
  },
  {
    id: 'pay-uuid-012',
    estimate_id: 'est-uuid-015',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'card',
    transaction_id: 'TX_CARD_44556677',
    paid_at: '2026-05-03T11:00:00Z',
    created_at: '2026-05-02T13:00:00Z',
    memo: '한강빌딩 난방 스팀 분기 헤더 플랜지 부식 실측비.'
  },
  {
    id: 'pay-uuid-013',
    estimate_id: 'est-uuid-016',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제완료',
    payment_provider: 'bank',
    transaction_id: 'TX_BANK_88990011',
    paid_at: '2026-05-06T10:00:00Z',
    created_at: '2026-05-05T09:30:00Z',
    memo: '세진화학 솔벤트 공급 메인 분기 씰 실측비.'
  },
  {
    id: 'pay-uuid-014',
    estimate_id: 'est-uuid-017',
    payment_type: '프로젝트 사전진단비',
    amount: 1500000,
    payment_status: '결제완료',
    payment_provider: 'card',
    transaction_id: 'TX_CARD_12123434',
    paid_at: '2026-05-09T14:00:00Z',
    created_at: '2026-05-08T15:00:00Z',
    memo: 'ABC식품 소스 가열 스팀 라인 증설 타당성 검토비.'
  },
  {
    id: 'pay-uuid-015',
    estimate_id: 'est-uuid-018',
    payment_type: '출장견적비',
    amount: 300000,
    payment_status: '결제대기',
    created_at: '2026-05-12T11:00:00Z',
    memo: '태양에너지 스크레이핑 여과기 차압 밸브 실측 출장비 (결제대기중)'
  }
];

// 5. 현장 실측 방문 관리 모의 데이터 (10건)
export const mockSiteVisits: SiteVisit[] = [
  {
    id: 'visit-uuid-001',
    estimate_id: 'est-uuid-001',
    visit_date: '2025-12-08',
    visitor_name: '김철수 부장',
    visit_purpose: '배관 노후화 및 누설점 실측',
    visit_status: '완료',
    visit_result: '3라인 메인 파이프 하단 200mm 균열 심화 확인. SUS304 스케줄 10 자재 제안.',
    site_memo: '천장 배관 지지 빔 앵커 부식 있음. 지지대 보강 시공 WBS 추가 요망.',
    risk_memo: '고소작업차 진입을 위해 공정 로터리 일부 철거 협의됨.',
    next_action: '12월 10일까지 최종 ISO 상세도면 및 견적 WBS 작성 송부.',
    created_at: '2025-12-05T09:30:00Z'
  },
  {
    id: 'visit-uuid-002',
    estimate_id: 'est-uuid-002',
    visit_date: '2025-12-24',
    visitor_name: '홍길동 대표',
    visit_purpose: '초순수 DIW 루프 연결 정밀 치수 검사',
    visit_status: '완료',
    visit_result: '크린룸 Class 100 기준 충족. EP 가공 배관 용접 시 퍼지 시간 확보 가능 확인.',
    site_memo: '배양기 전단 분접구 협소. 스윙 체크 밸브 배치 동선 변경 요구.',
    risk_memo: '공정 중단Tie-in을 위한 주말 10시간 정전 한계 확인.',
    next_action: '용접 품질 보증서 및 시나리오 송부.',
    created_at: '2025-12-20T10:15:00Z'
  },
  {
    id: 'visit-uuid-003',
    estimate_id: 'est-uuid-003',
    visit_date: '2026-01-13',
    visitor_name: '김철수 부장',
    visit_purpose: '황산 유하 배관 화학 부식 분석',
    visit_status: '완료',
    visit_result: '황산 잔류로 인한 강도 저하 우려 확인. PTFE 테플론 라인 적용 제안 결정.',
    site_memo: '용접 포인트 최소화 필요. 기성 플랜지 이음 구간 실측.',
    risk_memo: '독성 유체 배출을 위한 안전 가스 퍼지 가이드라인 설계 요구.',
    next_action: '1월 15일까지 PTFE 라이닝 관 사양서 견적 작성.',
    created_at: '2026-01-10T14:20:00Z'
  },
  {
    id: 'visit-uuid-004',
    estimate_id: 'est-uuid-004',
    visit_date: '2026-01-21',
    visitor_name: '이영희 대리',
    visit_purpose: '물류센터 천장 메인 소화관 동파 실측',
    visit_status: '완료',
    visit_result: '150m 구간 보온재 완전 탈락 상태 확인. 메탈 열선 1.5w/m 설계 적합.',
    site_memo: '천장 높이 8.5m로 시저스 리프트 반입 경로 확인 완료.',
    risk_memo: '겨울철 최저 영하 12도 감안하여 메탈히터 릴레이 이중화 권장.',
    next_action: '견적서 작성 및 수주 품의 지원.',
    created_at: '2026-01-18T11:00:00Z'
  },
  {
    id: 'visit-uuid-005',
    estimate_id: 'est-uuid-006',
    visit_date: '2026-02-24',
    visitor_name: '홍길동 대표',
    visit_purpose: '대형 매니폴더 Hot-tapping 가능성 진단',
    visit_status: '완료',
    visit_result: '기존 배관 진원도 99%로 핫태핑 피팅 슬리브 안착 가능 진단.',
    site_memo: '12시간 셧다운 내 매니폴더 4개 탭 천공 가능 타임라인 조율.',
    risk_memo: '차단 시 배관 물 빼기 드레인 밸브 개방 한계 협의.',
    next_action: '천공 장비 수급 및 WBS 송부.',
    created_at: '2026-02-20T16:00:00Z'
  },
  {
    id: 'visit-uuid-006',
    estimate_id: 'est-uuid-007',
    visit_date: '2026-03-09',
    visitor_name: '김철수 부장',
    visit_purpose: '고압 가스 공급부 진동 주파수 실측',
    visit_status: '완료',
    visit_result: '펌프 기동 시 25Hz 대역 진동 증폭. 유연 플렉시블 조인트 2단 적용 제안.',
    site_memo: '기계실 펌프 흡입 편심관 리듀서 재설계 필요성 전달함.',
    risk_memo: '방진 스프링 베이스 하단 패드 신설 공간 필요.',
    next_action: '3D ISO 간섭 검토 뷰 도면 작성.',
    created_at: '2026-03-05T13:30:00Z'
  },
  {
    id: 'visit-uuid-007',
    estimate_id: 'est-uuid-009',
    visit_date: '2026-04-05',
    visitor_name: '이영희 대리',
    visit_purpose: '클린룸 질소 배관 분접 여건 실측',
    visit_status: '완료',
    visit_result: 'Class 100 무균실 가스 분기 라인 이물 차단 구조 확인.',
    site_memo: 'EP 자재 보관을 위한 클린 텐트 설치 공간 조율.',
    risk_memo: '산소 농도 경보기 설치 필요성 식별.',
    next_action: '견적서 및 자재 리스트 발송.',
    created_at: '2026-04-02T14:00:00Z'
  },
  {
    id: 'visit-uuid-008',
    estimate_id: 'est-uuid-012',
    visit_date: '2026-04-25',
    visitor_name: '김철수 부장',
    visit_purpose: '칠러 기계실 바이패스관 레이아웃 스캔',
    visit_status: '완료',
    visit_result: '기존 관경 80A 밸브 노후 확인. 신속한 차단 바이패스관 65A 스펙 확정.',
    site_memo: '작업 구간 기계실 출입구 폭 900mm로 대형 조립품 반입 불가 확인. 현장 조립 필요.',
    next_action: 'WBS 견적 산정.',
    created_at: '2026-04-22T09:30:00Z'
  },
  {
    id: 'visit-uuid-009',
    estimate_id: 'est-uuid-015',
    visit_date: '2026-05-04',
    visitor_name: '김철수 부장',
    visit_purpose: '난방 스팀 분기 헤더 플랜지 누수 진단',
    visit_status: '완료',
    visit_result: '스팀 플랜지 체결 볼트 부식 절단 상태. 볼트 전면 교체 및 고온 가스켓 대체 진단.',
    site_memo: '주민 소음 차단을 위해 주간 작업 시간 10시~17시 엄격 제한 확인.',
    next_action: '긴급 견적서 산출 완료.',
    created_at: '2026-05-02T13:00:00Z'
  },
  {
    id: 'visit-uuid-010',
    estimate_id: 'est-uuid-016',
    visit_date: '2026-05-08',
    visitor_name: '김철수 부장',
    visit_purpose: '솔벤트 공급 메인 분기 씰 실측',
    visit_status: '완료',
    visit_result: '방폭 규정 적용 구간. 비불꽃(방폭 전용) 유압 코킹 장비 사용 공법 수립.',
    risk_memo: '방폭 구역 가스 측정기 의무 휴대 교육 배정 필요.',
    next_action: '방폭 시공 계획서 작성 및 견적 대장 수립.',
    created_at: '2026-05-05T09:30:00Z'
  }
];
